In [8]:
import pandas as pd

url = "https://www.hacienda.cl/areas-de-trabajo/finanzas-internacionales/oficina-de-la-deuda-publica/estadisticas/caracteristicas-financieras-bonos-externos"

tablas = pd.read_html(url)
print(f"Se encontraron {len(tablas)} tablas en la página")
print(tablas[0])

Se encontraron 10 tablas en la página
                          Emisiones Global 2005 (USD) Global 2007 (USD)  \
0                     Fecha emisión         18-abr-02         18-abr-02
1                    Fecha de pagos  25-ene /  25-abr  23-ene /  23-jul
2                 Fecha vencimiento         25-jul-05         23-Jul-07
3    Madurez en la fecha de Emisión           3 a 3 m           5 a 3 m
4                 Monto (MM US$)(1)             300 €            US$600
5              Tasa carátula (% a.)            5,125%            5,625%
6   Tasa bono Tesoro EE.UU.  (% a.)            4,405%            4,510%
7                            Precio           99,632%           99,658%
8       Yield a la fecha de emisión            5,235%            5,670%
9              Spread carátula (pb)            83 (2)               116
10                     Pago capital          Al final          Al final
11                   Pago intereses  Semestrales  (3)  Semestrales  (3)
12                         Vigencia  Vencido y pagado  Vencido y pagado

       Global 2008 (USD) Global 2009 (USD) Global 2012 (USD)  \
0              28-ene-04         21-abr-99         11-Oct-01
1   28-ene-  abr-jul-oct  28-abr /  28-oct  11-Ene /  11-Jul
2              28-ago-08         28-Abr-09         11-Ene-12
3                    4 a              10 a          10 a 3 m
4                 US$600            US$500            US$650
5     Libor (3M) + 0,40%            6,875%            7,125%
6                      -            5,181%            4,660%
7                99,882%           99,864%           99,236%
8                      -            6,931%            7,220%
9                      -               175               256
10              Al final          Al final          Al final
11          Trimestrales       Semestrales  Semestrales  (3)
12      Vencido y pagado  Vencido y pagado  Vencido y pagado

   Global 2012  Reapertura (USD) Global 2013 (USD)
0                      30-Oct-02         08-ene-03
1               11-ene /  11-jul  15-ene /  15-jul
2                      11-ene-12         15-ene-13
3                        9 a 2 m              10 a
4                         US$100          US$1.000
5                         7,125%            5,500%
6                         3,963%            3,990%
7                        107,09%           99,091%
8                         6,113%            5,620%
9                            215               163
10                      Al final          Al final
11              Semestrales  (4)       Semestrales
12              Vencido y pagado  Vencido y Pagado

In [9]:
def limpiar_tabla(tabla: pd.DataFrame) -> pd.DataFrame:
    """Voltea la tabla: de 'campos como filas, bonos como columnas'
    a 'bonos como filas, campos como columnas'."""
    tabla = tabla.set_index("Emisiones")
    return tabla.transpose()

tablas_limpias = [limpiar_tabla(t) for t in tablas]
df_bonos = pd.concat(tablas_limpias)
df_bonos.index.name = "bono"
df_bonos = df_bonos.reset_index()

print(f"Total de bonos: {len(df_bonos)}")
print(df_bonos.columns.tolist())
df_bonos.head(10)

Total de bonos: 58
['bono', 'Fecha emisión', 'Fecha de pagos', 'Fecha vencimiento', 'Madurez en la fecha de Emisión', 'Monto (MM US$)(1)', 'Tasa carátula (% a.)', 'Tasa bono Tesoro EE.UU.  (% a.)', 'Precio', 'Yield a la fecha de emisión', 'Spread carátula (pb)', 'Pago capital', 'Pago intereses', 'Vigencia', 'Tasa bono Tesoro EE.UU. (% a.)', 'Tasa local bono Tesoro Chile (% a.)', 'Monto (MM)']

Emisiones,bono,Fecha emisión,Fecha de pagos,Fecha vencimiento,Madurez en la fecha de Emisión,Monto (MM US$)(1),Tasa carátula (% a.),Tasa bono Tesoro EE.UU. (% a.),Precio,Yield a la fecha de emisión,Spread carátula (pb),Pago capital,Pago intereses,Vigencia,Tasa bono Tesoro EE.UU. (% a.),Tasa local bono Tesoro Chile (% a.),Monto (MM)
0,Global 2005 (USD),18-abr-02,25-ene / 25-abr,25-jul-05,3 a 3 m,300 €,"5,125%","4,405%","99,632%","5,235%",83 (2),Al final,Semestrales (3),Vencido y pagado,NaN,NaN,NaN
1,Global 2007 (USD),18-abr-02,23-ene / 23-jul,23-Jul-07,5 a 3 m,US$600,"5,625%","4,510%","99,658%","5,670%",116,Al final,Semestrales (3),Vencido y pagado,NaN,NaN,NaN
2,Global 2008 (USD),28-ene-04,28-ene- abr-jul-oct,28-ago-08,4 a,US$600,"Libor (3M) + 0,40%",-,"99,882%",-,-,Al final,Trimestrales,Vencido y pagado,NaN,NaN,NaN
3,Global 2009 (USD),21-abr-99,28-abr / 28-oct,28-Abr-09,10 a,US$500,"6,875%","5,181%","99,864%","6,931%",175,Al final,Semestrales,Vencido y pagado,NaN,NaN,NaN
4,Global 2012 (USD),11-Oct-01,11-Ene / 11-Jul,11-Ene-12,10 a 3 m,US$650,"7,125%","4,660%","99,236%","7,220%",256,Al final,Semestrales (3),Vencido y pagado,NaN,NaN,NaN
5,Global 2012 Reapertura (USD),30-Oct-02,11-ene / 11-jul,11-ene-12,9 a 2 m,US$100,"7,125%","3,963%","107,09%","6,113%",215,Al final,Semestrales (4),Vencido y pagado,NaN,NaN,NaN
6,Global 2013 (USD),08-ene-03,15-ene / 15-jul,15-ene-13,10 a,US$1.000,"5,500%","3,990%","99,091%","5,620%",163,Al final,Semestrales,Vencido y Pagado,NaN,NaN,NaN
7,Global 2020 en USD,05-ago-10,05-feb / 05-ago,05-ago-20,10 a,US$739(6),"3,875%",NaN,"99,877%","3,890%",90,Al final,Semestrales,Vencido y pagado,"2,990%",N.A.,NaN
8,Global 2020 en CLP,05-ago-10,05-feb / 05-ago,05-ago-20,10 a,272.295,"5,50%",NaN,"100,00%","5,500%",-58,Al final,Semestrales,Vencido y pagado,N.A.,"6,08%",NaN
9,Global 2021 en USD,14-sep-11,14-mar / 14-sep,14-sep-21,10 a,US$561(6),"3,250%",NaN,"99,131%","3,343%",130,Al final,Semestrales,Vigente,"2,043%",N.A.,NaN

In [10]:
import re

def normalizar_nombre_columna(nombre: str) -> str:
    """Colapsa espacios múltiples a uno solo y quita espacios al inicio/final."""
    return re.sub(r"\s+", " ", nombre).strip()

df_bonos.columns = [normalizar_nombre_columna(c) for c in df_bonos.columns]
print(df_bonos.columns.tolist())

['bono', 'Fecha emisión', 'Fecha de pagos', 'Fecha vencimiento', 'Madurez en la fecha de Emisión', 'Monto (MM US$)(1)', 'Tasa carátula (% a.)', 'Tasa bono Tesoro EE.UU. (% a.)', 'Precio', 'Yield a la fecha de emisión', 'Spread carátula (pb)', 'Pago capital', 'Pago intereses', 'Vigencia', 'Tasa bono Tesoro EE.UU. (% a.)', 'Tasa local bono Tesoro Chile (% a.)', 'Monto (MM)']

In [11]:
print(df_bonos["bono"].value_counts().head(10))

bono
Global 2031 en USD                3
Global 2031 en Euro Reapertura    2
Global 2036 en EUR                2
Global 2037 en USD                2
Global 2035 en EUR                2
Global 2032 en EUR                2
Global 2032 en EUR.1              2
Global 2008 (USD)                 1
Global 2020  en CLP               1
Global 2021  en USD               1
Name: count, dtype: int64

In [12]:
duplicados_exactos = df_bonos[df_bonos.duplicated(keep=False)].sort_values("bono")
print(duplicados_exactos[["bono", "Fecha emisión", "Fecha vencimiento"]])

                    bono Fecha emisión Fecha vencimiento
41    Global 2031 en USD     13-ene-26         13-abr-31
55    Global 2031 en USD     13-ene-26         13-abr-31
39    Global 2032 en EUR     14-ene-25         14-ene-32
53    Global 2032 en EUR     14-ene-25         14-ene-32
42  Global 2032 en EUR.1     14-ene-26         14-abr-32
56  Global 2032 en EUR.1     14-ene-26         14-abr-32
40    Global 2035 en EUR     01-jul-25         01-jul-35
54    Global 2035 en EUR     01-jul-25         01-jul-35
43    Global 2036 en EUR     14-ene-26         14-abr-36
57    Global 2036 en EUR     14-ene-26         14-abr-36
38    Global 2037 en USD     13-ene-25         13-ene-37
52    Global 2037 en USD     13-ene-25         13-ene-37

In [13]:
print(f"Filas antes: {len(df_bonos)}")
df_bonos = df_bonos.drop_duplicates()
print(f"Filas después: {len(df_bonos)}")

Filas antes: 58
Filas después: 52

In [14]:
df_bonos["bono"] = df_bonos["bono"].str.replace(r"\.\d+$", "", regex=True)
print(df_bonos[["bono", "Fecha emisión", "Fecha vencimiento"]].tail(15))

                   bono Fecha emisión Fecha vencimiento
37   Global 2041 en USD      4-may-21          7-may-41
38   Global 2037 en USD     13-ene-25         13-ene-37
39   Global 2032 en EUR     14-ene-25         14-ene-32
40   Global 2035 en EUR     01-jul-25         01-jul-35
41   Global 2031 en USD     13-ene-26         13-abr-31
42   Global 2032 en EUR     14-ene-26         14-abr-32
43   Global 2036 en EUR     14-ene-26         14-abr-36
44   Global 2027 en USD     27-ene-22         31-ene-27
45   Global 2034 en USD     27-ene-22         31-ene-34
46   Global 2052 en USD     27-ene-22         31-ene-52
47   Global 2042 en USD     02-mar-22       07-mar-2042
48   Global 2036 en USD     27-jun-23          5-ene-36
49   Global 2054 en USD     27-jun-23          5-ene-54
50  Global 2034 en Euro     28-jun-23          5-jul-34
51   Global 2029 en USD     17-ene-24       22-ene-2029

In [17]:
df_bonos["monto_raw"] = df_bonos["Monto (MM US$)(1)"].fillna(df_bonos["Monto (MM)"])
print(df_bonos[["bono", "Monto (MM US$)(1)", "Monto (MM)", "monto_raw"]].head(35))

                                 bono Monto (MM US$)(1) Monto (MM)  monto_raw
0                   Global 2005 (USD)             300 €        NaN      300 €
1                   Global 2007 (USD)            US$600        NaN     US$600
2                   Global 2008 (USD)            US$600        NaN     US$600
3                   Global 2009 (USD)            US$500        NaN     US$500
4                   Global 2012 (USD)            US$650        NaN     US$650
5       Global 2012  Reapertura (USD)            US$100        NaN     US$100
6                   Global 2013 (USD)          US$1.000        NaN   US$1.000
7                 Global 2020  en USD         US$739(6)        NaN  US$739(6)
8                 Global 2020  en CLP           272.295        NaN    272.295
9                 Global 2021  en USD         US$561(6)        NaN  US$561(6)
10     Global 2020  en CLP Reapertura           162.050        NaN    162.050
11                Global 2022  en USD         US$634(6)        NaN  US$634(6)
12                Global 2042  en USD            US$750        NaN     US$750
13                Global 2025  en USD         US$758(6)        NaN  US$758(6)
14               Global 2025  en Euro             800 €        NaN      800 €
15  Global 2025  en Euro (Reapertura)             440 €        NaN      440 €
16               Global 2030  en Euro             950 €        NaN      950 €
17                Global 2026  en USD          US$1.349        NaN   US$1.349
18               Global 2026  en Euro           1.200 €        NaN    1.200 €
19                Global 2047  en USD          US$1.541        NaN   US$1.541
20  Global 2030 en Euro  (Reapertura)             700 €        NaN      700 €
21                 Global 2028 en USD          US$2.000        NaN   US$2.000
22                Global 2029 en Euro              830€        NaN       830€
23                Global 2050  en USD               NaN   US$1.418   US$1.418
24                Global 2031 en Euro               NaN       861€       861€
25                Global 2040 en Euro               NaN     1.269€     1.269€
26                 Global 2032 en USD               NaN     US$750     US$750
27     Global 2031 en Euro Reapertura               NaN       694€       694€
28      Global 2050 en USD Reapertura               NaN     US$900     US$900
29    Global 2025  en Euro Reapertura               NaN       500€       500€
30                 Global 2031 en USD               NaN   US$1.458   US$1.458
31     Global 2031 en Euro Reapertura               NaN       400€       400€
32                Global 2051 en Euro               NaN     1.250€     1.250€
33      Global 2032 en USD Reapertura               NaN     US$750     US$750
34                 Global 2061 en USD               NaN   US$1.500   US$1.500

In [18]:
print(df_bonos["monto_raw"].isna().sum())

0

In [19]:
df_bonos = df_bonos.drop(columns=["Monto (MM US$)(1)", "Monto (MM)"])

In [20]:
print(df_bonos.shape)
print(df_bonos.columns.tolist())
print()
df_bonos

(52, 16)
['bono', 'Fecha emisión', 'Fecha de pagos', 'Fecha vencimiento', 'Madurez en la fecha de Emisión', 'Tasa carátula (% a.)', 'Tasa bono Tesoro EE.UU. (% a.)', 'Precio', 'Yield a la fecha de emisión', 'Spread carátula (pb)', 'Pago capital', 'Pago intereses', 'Vigencia', 'Tasa bono Tesoro EE.UU. (% a.)', 'Tasa local bono Tesoro Chile (% a.)', 'monto_raw']

,bono,Fecha emisión,Fecha de pagos,Fecha vencimiento,Madurez en la fecha de Emisión,Tasa carátula (% a.),Tasa bono Tesoro EE.UU. (% a.),Precio,Yield a la fecha de emisión,Spread carátula (pb),Pago capital,Pago intereses,Vigencia,Tasa bono Tesoro EE.UU. (% a.),Tasa local bono Tesoro Chile (% a.),monto_raw
0,Global 2005 (USD),18-abr-02,25-ene / 25-abr,25-jul-05,3 a 3 m,"5,125%","4,405%","99,632%","5,235%",83 (2),Al final,Semestrales (3),Vencido y pagado,NaN,NaN,300 €
1,Global 2007 (USD),18-abr-02,23-ene / 23-jul,23-Jul-07,5 a 3 m,"5,625%","4,510%","99,658%","5,670%",116,Al final,Semestrales (3),Vencido y pagado,NaN,NaN,US$600
2,Global 2008 (USD),28-ene-04,28-ene- abr-jul-oct,28-ago-08,4 a,"Libor (3M) + 0,40%",-,"99,882%",-,-,Al final,Trimestrales,Vencido y pagado,NaN,NaN,US$600
3,Global 2009 (USD),21-abr-99,28-abr / 28-oct,28-Abr-09,10 a,"6,875%","5,181%","99,864%","6,931%",175,Al final,Semestrales,Vencido y pagado,NaN,NaN,US$500
4,Global 2012 (USD),11-Oct-01,11-Ene / 11-Jul,11-Ene-12,10 a 3 m,"7,125%","4,660%","99,236%","7,220%",256,Al final,Semestrales (3),Vencido y pagado,NaN,NaN,US$650
5,Global 2012 Reapertura (USD),30-Oct-02,11-ene / 11-jul,11-ene-12,9 a 2 m,"7,125%","3,963%","107,09%","6,113%",215,Al final,Semestrales (4),Vencido y pagado,NaN,NaN,US$100
6,Global 2013 (USD),08-ene-03,15-ene / 15-jul,15-ene-13,10 a,"5,500%","3,990%","99,091%","5,620%",163,Al final,Semestrales,Vencido y Pagado,NaN,NaN,US$1.000
7,Global 2020 en USD,05-ago-10,05-feb / 05-ago,05-ago-20,10 a,"3,875%",NaN,"99,877%","3,890%",90,Al final,Semestrales,Vencido y pagado,"2,990%",N.A.,US$739(6)
8,Global 2020 en CLP,05-ago-10,05-feb / 05-ago,05-ago-20,10 a,"5,50%",NaN,"100,00%","5,500%",-58,Al final,Semestrales,Vencido y pagado,N.A.,"6,08%",272.295
9,Global 2021 en USD,14-sep-11,14-mar / 14-sep,14-sep-21,10 a,"3,250%",NaN,"99,131%","3,343%",130,Al final,Semestrales,Vigente,"2,043%",N.A.,US$561(6)
10,Global 2020 en CLP Reapertura,05-ago-10,05-feb / 05-ago,05-ago-20,"8 a, 11 m","5,50%",NaN,"108,02%","4,40%",-55,Al final,Semestrales,Vencido y pagado,N.A.,"4,95%",162.050
11,Global 2022 en USD,30-oct-12,30-abr/ 30-oct,30-oct-22,10 a,"2,25%",NaN,"98,858%","2,379%",55,Al final,Semestrales,Vigente,"1,83%","5,4%",US$634(6)
12,Global 2042 en USD,30-oct-12,30-abr/ 30-oct,30-oct-42,30 a,"3,625%",NaN,"98,398%","3,714%",75,Al final,Semestrales,Vigente,"2,96%",N.A.,US$750
13,Global 2025 en USD,12-dic-14,27-mar / 27-sep,27-mar-25,10 a,"3,125%",NaN,"99,466%","3,185%",90,Al final,Semestrales,Vigente,"2,285%",N.A.,US$758(6)
14,Global 2025 en Euro,12-dic-14,30-ene,30-ene-25,11 a,"1,625%",NaN,"98,892%","1,745%",75 (5),Al final,Anual,Vigente,N.A.,N.A.,800 €
15,Global 2025 en Euro (Reapertura),12-dic-14,30-ene,30-ene-25,"9,7 a","1,625%",NaN,"101,366%","1,472%",60 (5),Al final,Anual,Vigente,N.A.,N.A.,440 €
16,Global 2030 en Euro,27-may-15,27-may,27-may-30,15 a,"1,875%",NaN,"98,127%","2,021%",85 (5),Al final,Anual,Vigente,N.A.,N.A.,950 €
17,Global 2026 en USD,21-ene-16,21-ene / 21-jul,21-ene-26,10 a,"3,125%",NaN,"97,627%","3,407%",130,Al final,Semestrales,Vigente,"2,107%",N.A.,US$1.349
18,Global 2026 en Euro,20-ene-16,20-ene,20-ene-26,10 a,"1,75%",NaN,"98,056%","1,966%",110 (5),Al final,Anual,Vigente,N.A.,N.A.,1.200 €
19,Global 2047 en USD,21-jun-17,21-ene/21-dic,21-jun-47,30 a,3.86%,"2,869%",99.841%,3.86%,100,Al final,Semestrales,Vigente,NaN,NaN,US$1.541
20,Global 2030 en Euro (Reapertura),27-may-15,27-may,27-may-30,13 a,"1,875%",N.A.,103.972%,1.534%,50(5),Al final,Anual,Vigente,NaN,NaN,700 €
21,Global 2028 en USD,6-feb-18,6-feb/6-ago,06-feb-28,10a,"3,24%","2,697%","99,941%","3,247%",55,Al final,Semestrales,Vigente,NaN,NaN,US$2.000
22,Global 2029 en Euro,1-feb-18,1-feb,1-feb-29,11a,"1,44%",n.a.,"99,454%","1,449%",89,Al final,Anual,Vigente,NaN,NaN,830€
23,Global 2050 en USD,25-jun-19,25-ene/25-jul,25-ene-50,30a 7m,"3,50%","2,58%","99,439%","3,53%",95,Al final,Semestrales,Vigente,NaN,NaN,US$1.418
24,Global 2031 en Euro,2-jul-19,2-jul,02-jul-31,12a,"0,830%",NaN,"100,000%","0,830%",50,Al final,Anuales,Vigente,NaN,NaN,861€
25,Global 2040 en Euro,29-ene-20,29-ene,29-ene-40,20a,"1,25%",NaN,"99,142%","1,299%",80,Al final,Anuales,Vigente,NaN,NaN,1.269€
26,Global 2032 en USD,27-ene-20,27-ene/27-jul,27-ene-32,12a,"2,55%","1,771%","99,784%","2,571%",80,Al final,Semestrales,Vigente,NaN,NaN,US$750
27,Global 2031 en Euro Reapertura,2-jul-19,2-jul,02-jul-31,11a6m,"0,830%",NaN,"101,477%","0,695%",50,Al final,Anuales,Vigente,NaN,NaN,694€
28,Global 2050 en USD Reapertura,25-jun-19,25-ene/25-jul,25-ene-50,30a,"3,500%","2,225%","104,277%","3,275%",105,Al final,Semestrales,Vigente,NaN,NaN,US$900
29,Global 2025 en Euro Reapertura,12-dic-14,30-ene,30-ene-25,5a,"1,625%",NaN,"102,098%","1,165%",150,Al final,Anual,Vigente,NaN,NaN,500€
30,Global 2031 en USD,12-may-20,31-ene/31-jul,31-ene-31,10a8m,"2,450%","0,654%","99,958%","2,454%",180,Al final,Semestrales,Vigente,NaN,NaN,US$1.458
31,Global 2031 en Euro Reapertura,22-ene-21,2-jul,02-jul-31,10a6m,"0,830%",NaN,"104,399%","0,399%",60,Al final,Anuales,Vigente,NaN,NaN,400€
32,Global 2051 en Euro,22-ene-21,22-ene,22-ene-51,30a,"1,25%",NaN,"98,814%","1,298%",125,Al final,Anuales,Vigente,NaN,NaN,1.250€
33,Global 2032 en USD Reapertura,22-ene-21,27-ene/27-jul,27-ene-32,11a,"2,55%","1,069%","105,682%","1,962%",87,Al final,Semestrales,Vigente,NaN,NaN,US$750
34,Global 2061 en USD,22-ene-21,22-ene/22-jul,22-ene-2061,40a,"3,10%","1,846%","99,636%","3,116%",127,Al final,Semestrales,Vigente,NaN,NaN,US$1.500
35,Global 2053 en USD Formosa,30-mar-21,15-abr/15-oct,15-abr-53,32a,"3,50%","2,381%","100,000%","3,500%",112,Al final,Semestrales,Vigente,NaN,NaN,US$1.500
36,Global 2031 en USD Reapertura,4-may-21,31-ene/31-jul,31-ene-31,10a,"2,45%","1,591%","109,922%","2,341%",75,Al final,Semestrales,Vigente,NaN,NaN,US$300
37,Global 2041 en USD,4-may-21,7-may/7-nov,7-may-41,20a,"3,10%","2,152%","97,060%","3,302%",115,Al final,Semestrales,Vigente,NaN,NaN,US$1.700
38,Global 2037 en USD,13-ene-25,13-ene/13-jul,13-ene-37,12a,"4,95%",NaN,"99,24%","5,739%",1375,Al final,Semestrales,Vigente,NaN,NaN,US$1.600
39,Global 2032 en EUR,14-ene-25,01-jul,14-ene-32,7a,"3,75%",NaN,"99,66%","3,806%",105,Al final,Anuales,Vigente,NaN,NaN,1.700 €
40,Global 2035 en EUR,01-jul-25,14-jul,01-jul-35,10a,"3,80%",NaN,"99,67%","3,841%",130,Al final,Anuales,Vigente,NaN,NaN,1.300 €
41,Global 2031 en USD,13-ene-26,13-abr/13-oct,13-abr-31,5a,"4,35%",NaN,"99,90%","4,37%",68,Al final,Semestrales,Vigente,NaN,NaN,US$850
42,Global 2032 en EUR,14-ene-26,14-abr,14-abr-32,6a,"3,38%",NaN,"99,54%","3,46%",85,Al final,Anuales,Vigente,NaN,NaN,1.500 €
43,Global 2036 en EUR,14-ene-26,14-abr,14-abr-36,10a,"3,88%",NaN,"99,57%","3,93%",105,Al final,Anuales,Vigente,NaN,NaN,1.500 €
44,Global 2027 en USD,27-ene-22,7-may/7-nov,31-ene-27,5a,"0,10%",NaN,"98,932%","0,296%",60 (5),Al final,Semestrales,Vigente,NaN,NaN,US$1.500
45,Global 2034 en USD,27-ene-22,7-may/7-nov,31-ene-34,15a,"1,30%",NaN,"99,865%","1,310%",110 (5),Al final,Semestrales,Vigente,NaN,NaN,US$1.500
46,Global 2052 en USD,27-ene-22,7-may/7-nov,31-ene-52,30a,"2,55%",NaN,"99,723%","2,577%",130,Al final,Semestrales,Vigente,NaN,NaN,US$1.000
47,Global 2042 en USD,02-mar-22,7-mar/7-sep,07-mar-2042,20a,"4,34%",NaN,"99,426%","4,346%",200,Al final,Semestrales,Vigente,NaN,NaN,US$2.000
48,Global 2036 en USD,27-jun-23,5-ene/5-jul,5-ene-36,12a,"4,95%",NaN,"99,558%","4,998%",123,Al final,Semestrales,Vigente,NaN,NaN,US$1.650
49,Global 2054 en USD,27-jun-23,5-ene/5-jul,5-ene-54,20a,"5,33%",NaN,"99,925%","5,335%",148,Al final,Semestrales,Vigente,NaN,NaN,US$1.482
50,Global 2034 en Euro,28-jun-23,5-jul,5-jul-34,10a,"4,125%",NaN,"99,212%","4,216%",190,Al final,Anuales,Vigente,NaN,NaN,1.176 €
51,Global 2029 en USD,17-ene-24,22-ene/22-jul,22-ene-2029,5a,"4,85%",NaN,"99,903%","4,872%",85,Al final,Semestrales,Vigente,NaN,NaN,US$1.700